---
name: 'ansible-lint'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: {}
jobs:
  build:
    name: 'Ansible Lint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - name: 'Run ansible-lint'
        uses: 'ansible/ansible-lint@main'
...
