---
name: 'gitleaks'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'
  push: {}
  workflow_dispatch: {}

jobs:
  gitleaks:
    name: 'gitleaks'
    permissions:
      contents: 'write'
      pull-requests: 'write'
      checks: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0
      - uses: 'gitleaks/gitleaks-action@v2'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
...
