---
name: 'markdown link check'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build:
    name: 'markdown-link-check'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@master'
      - uses: 'gaurav-nelson/github-action-markdown-link-check@v1'
        with:
          folder-path: './'
          config-file: '.markdown-link-check.json'
...
